### ISSUE TITLE
NPM install fails on mac

### ISSUE THREAD

**Issue by etheya** [wolfendale/prototype_kit#21]
This is failing for me on mac now due to the git dependencies on GOV.uk elements...

**Comment by wolfendale** [comment]
Could you add the error log from terminal on here too please?

**Comment by etheya** [comment]
Rename to .log if need be.
[npm-debug.txt](https://github.com/wolfendale/prototype_kit/files/25350/npm-debug.txt)

**Comment by roblav** [comment]
After testing this it looks like the simplest solution is to use an additional command to install the govuk_elements repo after npm install fails the first time, like this:
'''
npm install alphagov/govuk_elements
'''

**Comment by wolfendale** [comment]
Hmm any idea why this fixes the problem? I can't see a sensible reason why this would break at npm install but then work on its own command. If this is actually a problem with npm we should raise an issue with them

**Comment by etheya** [comment]
Made sure xcode was installed on my machine and have tried this again... same errors im afraid...

**Comment by joelanman** [comment]
@etheya have you actually run Xcode? You need to accept T&Cs there for it to work on the command line I think.

**Comment by etheya** [comment]
Yeah Xcode was running... same issues.

**Comment by roblav** [comment]
I've just installed the latest version of npm using the npm installer from https://nodejs.org/en/download/ and everything worked straight away without using the additional 'npm install alphagov/govuk_elements'.
Can you confirm you have NodeJS version v4.1.2 or higher installed.

**Comment by etheya** [comment]
Im running 4.2.0...

**Comment by etheya** [comment]
Im running El Capitain too... but can't see that would be an issue..

**Comment by etheya** [comment]
Going to try installing the latest 4.2.2 just to see if that works

**Comment by etheya** [comment]
Installed latest node and tried from a fresh start... same issues.. 

module.js:339
    throw err;
    ^

Error: Cannot find module 'merge-stream'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/Etheya/hmrc/proto/gulpfile.js:4:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by wolfendale** [comment]
This seems like a different problem from what you showed me before. Very strange.

Did you do:
```
npm install -g gulp
npm install
```

After you reinstalled node?

**Comment by etheya** [comment]
Yup… just throws out loads of errors..

Kind Regards

Brian Coult
Mobile Consultant | Designer | ExpressionEngine Developer
Etheya Digital Creativity Ltd

t. 07463 240076
e. brian@etheya-digitalcreativity.com <mailto:brian@etheya-digitalcreativity.com>
w. www.etheya-digitalcreativity.com <http://www.etheya-digitalcreativity.com/>

Skype: etheya-bc
LinkedIn: http://www.linkedin.com/pub/brian-coult/3/902/127 <http://www.linkedin.com/pub/brian-coult/3/902/127>

**Comment by etheya** [comment]
Will try again just to make sure.... don't forget I'm on El Capitain too... not sure if that makes any difference.

**Comment by etheya** [comment]
Okay this is no longer a bug, however we do need some documentation around this as it wasnt asking me for the agreement using Tower UI.... compared to using the git command line.

**Comment by etheya** [comment]
Cant add a label for needs documentation that i can see.

**Comment by wolfendale** [comment]
I've added a documentation label and you can add/edit labels for the project [here](http://www.github.com/wolfendale/prototype_kit/labels)

**Comment by roblav** [comment]
I've updated the documentation here https://github.com/wolfendale/prototype_kit/wiki/Getting-Started

**Comment by roblav** [comment]
@etheya could you close this issue if you're happy with the update to the wiki
